apiVersion: dataplane.openstack.org/v1beta1
kind: OpenStackDataPlaneService
metadata:
  name: cisco-opflex-agent-custom-service
spec:
  label: dataplane-deployment-cisco-opflex-agent-service
  openStackAnsibleEERunnerImage: registry.connect.redhat.com/noiro/combined-ansibleee-runner:latest
  playbook: osp.edpm.opflex_agent
