apiVersion: dataplane.openstack.org/v1beta1
kind: OpenStackDataPlaneService
metadata:
  name: ciscoaci-lldp-agent-service
spec:
  label: dataplane-deployment-ciscoaci-lldp-agent-service
  openStackAnsibleEERunnerImage: registry.connect.redhat.com/noiro/combined-ansibleee-runner:latest
  playbook: osp.edpm.lldp
  caCerts: combined-ca-bundle
  edpmServiceType: ciscoaci-lldp-agent-service
