apiVersion: dataplane.openstack.org/v1beta1
kind: OpenStackDataPlaneService
metadata:
  name: neutron-opflex-agent-custom-service
spec:
  label: dataplane-deployment-neutron-opflex-agent-service
  openStackAnsibleEERunnerImage: registry.connect.redhat.com/noiro/combined-ansibleee-runner:latest
  playbook: osp.edpm.neutron_opflex_agent
  caCerts: combined-ca-bundle
  edpmServiceType: neutron-opflex-agent-custom-service
  dataSources:
    - secretRef:
        name: rabbitmq-transport-url-neutron-neutron-transport
